### ISSUE TITLE
Workflow directoriesFilesChangePR.yml failed with the wrong openjdk_testRepo

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#2291]
Workflow directoriesFilesChangePR.yml failed with the wrong openjdk_testRepo.

`openjdk_testRepo: '${{ github.event.pull_request.head.repo.full_name }}:${GITHUB_HEAD_REF}'` looks like `GITHUB_HEAD_REF` was not set.

https://github.com/AdoptOpenJDK/openjdk-tests/pull/2287/checks?check_run_id=1931685928

```
Run AdoptOpenJDK/run-aqa@v1
  with:
    build_list: openjdk
    target: _sanity.regular
    jdksource: install-jdk
    version: 8
    openjdk_testRepo: adamfarley/openjdk-tests:${GITHUB_HEAD_REF}
    tkg_Repo: TKG:master
```
